name: CI Workflow

on:
    push:
        branches: [ main ]
    pull_request:
        branches: [ main ]

jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Set up Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: 16

            - name: Install dependencies
              run: npm install

            - name: Run tests
              run: npx jest
              continue-on-error: true #Permite continuar con el workflow si hay un error

            - name: Notify on Failure
              if: ${{ failure() }}
              run: echo "Tests failed! Please check the logs for more details."

            - name: Save logs on failure
              if: ${{ failure()}}
              run: |
                  mkdir -p logs
                  echo "Logs for failed tests" > logs/test-failure.log

            - name: Upload test logs
              if: ${{ failure() }}
              uses: actions/upload-artifact@v3
              with:
                  name: test-logs
                  path: logs/

            - name: Always run cleanup
              if: always()
              run: echo "Cleaning up resources..."