name: CI Workflow 2
on:
    push:
        branches: [ main ]
    pull_request:
        branches: [ main ]
jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Run tests
              run: echo "Tests passed!"

            - name: Use a secret
              env:
                  MY_SECRET: ${{ secrets.KEY_PRUEBA }}
              run: echo $MY_SECRET