name: Docker Build and run


on:
    push:
        branches:
            - main

jobs:
    docker:
        runs-on: ubuntu-latest

        steps:
            #Verificar el código fuente
            - name: Checkout code
              uses: actions/checkout@v3

            #Construir la imagen Docker
            - name: Build Docker image
              run: |
                docker build -t my-docker-image:latest .

            - name: Run Docker container
              run: |
                docker run --rm my-docker-image:latest