name: Merge to Release and Main

on:
  pull_request:
    branches:
      - merge
    types:
      - closed

jobs:
  merge_and_tag:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Git user with PR author details
        run: |
          git config user.name "${{ github.event.pull_request.user.login }}"
          git config user.email "${{ github.event.pull_request.user.email }}"

      - name: Merge into release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git checkout release
          git merge --no-ff merge -m "Merging merge into release"
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/DavidFigueroaRod/pruebaNodeJSGithubActions.git
          git push origin release

      - name: Generate version
        id: version
        run: echo "::set-output name=VERSION::$(date +'%Y%m%d%H%M%S')"
        
      - name: Create tag for new version
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git tag ${{ steps.version.outputs.VERSION }}
          git push origin ${{ steps.version.outputs.VERSION }}

      - name: Merge into main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git checkout main
          git merge --no-ff release -m "Syncing release with main"
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/DavidFigueroaRod/pruebaNodeJSGithubActions.git
          git push origin main
