name: Workflow Padre

on:
    pull_request: 
        branches: [main]


jobs:
    call_child_workflow:
        uses: ./.github/workflows/workflow_hijo.yml
        with:
            name: "GitHub Actions"

#    call_child_workflow:
#         uses: ./.github/workflows/workflow_hijo.yml        
#         with:
#             name: "GitHub Actions"